runtime: custom
vm: true

skip_files:
  - ^(.*/)?.*/node_modules/.*$
  
manual_scaling:
  instances: 1
  
handlers:
- url: /tasks/delete-timedout-files
  script: ./src/app.js
  login: admin

- url: /.*
  script: ./src/app.js
